#!/usr/bin/env python3
"""Generate one self contained engine per skill and language.

    python3 scripts/build-engines.py           # write engines/
    python3 scripts/build-engines.py --check   # fail if anything is stale

An engine is what the floor consumes: one markdown file a person attaches to
a conversation, holding the router, one skill, and every reference and pack
file that skill needs. No second file to fetch, because the floor cannot
fetch one.

**The manifest is read, never inferred.** Each skill carries an
`engine.manifest` listing its dependencies by hand. A generator that worked
out dependencies by reading the skill's prose would be the same design that
failed four times on the markdown parser check, where a comment naming a
library and an import of it are indistinguishable to a regular expression.
The prose is still read, but only to *contradict* the manifest: a citation
the manifest does not carry is an error, because it would ship an engine
pointing at a file nobody attached.

Standard library only, like the rest of the engine seam.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "engines"

#: A path a skill cites. Same shape as app/verbatim_app/skills.py, on purpose:
#: two readers of one convention, and a skill that satisfies one satisfies the
#: other.
CITED = re.compile(
    r"\b(?:references/[\w.-]+\.md|locales/[\w<>.-]+/[\w.-]+\.md)\b")

#: Both spellings of the interview axis. The field was renamed and the frozen
#: app still writes the old one.
LANG_PLACEHOLDERS = ("<lang>", "<interview_language>", "<interface_language>")


def languages() -> list[str]:
    """Every shipped pack, `_template` excluded."""
    return sorted(d.name for d in (ROOT / "locales").iterdir()
                  if d.is_dir() and not d.name.startswith("_"))


def fill(path: str, lang: str) -> str:
    for placeholder in LANG_PLACEHOLDERS:
        path = path.replace(placeholder, lang)
    return path


def manifest(skill: Path) -> list[str]:
    """The declared dependencies of one skill, comments and blanks dropped."""
    lines = (skill / "engine.manifest").read_text(encoding="utf-8").splitlines()
    return [l.strip() for l in lines if l.strip() and not l.startswith("#")]


def dangling(engine: str, lang: str) -> list[str]:
    """Citations in the finished engine whose content is not in the engine.

    **This reads the product, not the intention.** An earlier version compared
    the manifest against the skill's own prose, which missed two whole
    surfaces: the root router, embedded in every engine, and the reference
    files themselves, which cite each other. Four of six engines shipped
    pointing at files nobody attached, and a citation of a file that did not
    exist anywhere passed every guard. Whatever the manifest says, what
    matters is whether a person holding this one file can follow every path it
    names, so that is what is checked.

    A path counts as carried when the engine holds a `## <path>` heading for
    it, which is how `one()` writes every embedded file.
    """
    carried = {line[3:].strip() for line in engine.splitlines()
               if line.startswith("## ")}
    missing = set()
    for cited in CITED.findall(engine):
        if fill(cited, lang) not in carried:
            missing.add(cited)
    return sorted(missing)


def one(skill: Path, lang: str) -> str:
    """The whole engine for one skill in one language, as text."""
    parts = [
        "<!-- Generated by scripts/build-engines.py. Do not edit here.\n"
        "     Edit the skill, its manifest, or the pack, then regenerate. -->\n",
        "# Verbatim engine: %s, %s\n" % (skill.name, lang),
        "Everything this engine needs is in this file. Attach it to a\n"
        "conversation and start. It writes no file and runs no code; where a\n"
        "host can do more, that is a convenience and never a promise.\n",
        "The pack below is the %s one. If the person writes their posts in\n"
        "another language, say so plainly: the output pack is not in this\n"
        "file, and the style rules that apply are the ones written here.\n"
        % lang,
        "\n---\n\n## Router\n",
        (ROOT / "SKILL.md").read_text(encoding="utf-8"),
        "\n---\n\n## Skill: %s\n" % skill.name,
        (skill / "SKILL.md").read_text(encoding="utf-8"),
    ]
    for cited in manifest(skill):
        resolved = fill(cited, lang)
        target = ROOT / resolved
        if not target.is_file():
            stand_in = ROOT / fill(cited, "en")
            if not stand_in.is_file():
                raise SystemExit("%s: %s names nothing" % (skill.name, cited))
            parts.append("\n---\n\n## %s\n\n> The %s pack has no %s. The English\n"
                         "> one stands in, and this line is the degradation\n"
                         "> being announced rather than hidden.\n"
                         % (resolved, lang, Path(cited).name))
            target = stand_in
        else:
            parts.append("\n---\n\n## %s\n" % resolved)
        parts.append(target.read_text(encoding="utf-8"))
    return "\n".join(parts)


def build(check: bool) -> int:
    OUT.mkdir(exist_ok=True)
    skills = sorted(p for p in (ROOT / "skills").iterdir()
                    if (p / "engine.manifest").is_file())
    stale, wrote = [], 0
    for skill in skills:
        for lang in languages():
            text = one(skill, lang)
            missing = dangling(text, lang)
            if missing:
                print("%s.%s points at what it does not carry: %s"
                      % (skill.name, lang, ", ".join(missing)), file=sys.stderr)
                print("  add it to skills/%s/engine.manifest, or stop citing "
                      "it as a path." % skill.name, file=sys.stderr)
                return 2
            path = OUT / ("%s.%s.md" % (skill.name, lang))
            if check:
                if not path.is_file() or path.read_text(encoding="utf-8") != text:
                    stale.append(path.relative_to(ROOT))
            else:
                path.write_text(text, encoding="utf-8")
                wrote += 1
                print("  %-34s %6d words" % (path.relative_to(ROOT),
                                             len(text.split())))
    if check:
        if stale:
            print("stale, regenerate with scripts/build-engines.py:",
                  file=sys.stderr)
            for path in stale:
                print("  %s" % path, file=sys.stderr)
            return 1
        return 0
    print("%d engines written" % wrote)
    return 0


if __name__ == "__main__":
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--check", action="store_true",
                    help="do not write; fail if any engine is out of date")
    raise SystemExit(build(ap.parse_args().check))
