#!/usr/bin/env bash
# Build Verbatim.app, a macOS launcher over this repository.
#
# The app it builds keeps its own clone of the repository under
# ~/Library/Application Support/Verbatim and fast-forwards it to origin/main
# on every launch: pushing to GitHub is the whole release process. It then
# serves one instance directory on loopback and opens the browser. The dev
# checkout you build from is never what the app runs; the clone is.
#
#   scripts/macos-app.sh <instance-dir> [port]
#
# The instance path and port are burned into the app. Rebuild to change them.
# Needs macOS (sips, iconutil), git and uv on the machine that will run it.
#
# The API key is read from the process environment, never from the instance,
# exactly as everywhere else in this bundle. A launched .app has almost no
# environment, so the launcher sources ~/.config/verbatim/env if it exists;
# put `ANTHROPIC_API_KEY=...` there, chmod 600, and nowhere else.
set -euo pipefail

INSTANCE="${1:?usage: scripts/macos-app.sh <instance-dir> [port]}"
PORT="${2:-8748}"
INSTANCE="$(cd "$INSTANCE" && pwd)"
HERE="$(cd "$(dirname "$0")/.." && pwd)"
REPO_URL="$(git -C "$HERE" remote get-url origin 2>/dev/null \
            || echo "https://github.com/alexis-morain/verbatim-linkedin.git")"

APP_HOME="/Applications"
[ -w "$APP_HOME" ] || APP_HOME="$HOME/Applications"
mkdir -p "$APP_HOME"
APP="$APP_HOME/Verbatim.app"

rm -rf "$APP"
mkdir -p "$APP/Contents/MacOS" "$APP/Contents/Resources"

# ---------------------------------------------------------------- the icon
ICONSET="$(mktemp -d)/verbatim.iconset"
mkdir -p "$ICONSET"
for size in 16 32 128 256 512; do
  sips -z "$size" "$size" "$HERE/assets/icon-1024.png" \
       --out "$ICONSET/icon_${size}x${size}.png" >/dev/null
  double=$((size * 2))
  sips -z "$double" "$double" "$HERE/assets/icon-1024.png" \
       --out "$ICONSET/icon_${size}x${size}@2x.png" >/dev/null
done
iconutil -c icns "$ICONSET" -o "$APP/Contents/Resources/verbatim.icns"

# ------------------------------------------------------------- the plist
cat > "$APP/Contents/Info.plist" <<PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"
  "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>CFBundleName</key><string>Verbatim</string>
  <key>CFBundleDisplayName</key><string>Verbatim</string>
  <key>CFBundleIdentifier</key><string>fr.morain.verbatim</string>
  <key>CFBundleVersion</key><string>2.0</string>
  <key>CFBundleExecutable</key><string>verbatim</string>
  <key>CFBundleIconFile</key><string>verbatim</string>
  <key>CFBundlePackageType</key><string>APPL</string>
  <key>LSMinimumSystemVersion</key><string>12.0</string>
</dict>
</plist>
PLIST

# ---------------------------------------------------------- the launcher
cat > "$APP/Contents/MacOS/verbatim" <<LAUNCHER
#!/bin/zsh
# Verbatim launcher, generated by scripts/macos-app.sh. Not hand edited:
# rebuild instead.
set -u
export PATH="/opt/homebrew/bin:/usr/local/bin:\$HOME/.local/bin:\$PATH"

SUPPORT="\$HOME/Library/Application Support/Verbatim"
REPO="\$SUPPORT/verbatim-linkedin"
LOG="\$HOME/Library/Logs/verbatim.log"
INSTANCE="$INSTANCE"
REPO_URL="$REPO_URL"
PORT=$PORT

fail() {
  /usr/bin/osascript -e "display dialog \\"\$1\\" with title \\"Verbatim\\" buttons {\\"OK\\"} default button 1" >/dev/null 2>&1
  exit 1
}

mkdir -p "\$SUPPORT"
echo "--- launch \$(date '+%Y-%m-%d %H:%M:%S')" >> "\$LOG"

command -v git >/dev/null || fail "git is not installed."
command -v uv  >/dev/null || fail "uv is not installed. See docs.astral.sh/uv"
[ -d "\$INSTANCE" ] || fail "The instance directory is gone: \$INSTANCE. Rebuild the app with scripts/macos-app.sh."

# The update. Every launch tracks origin/main exactly; offline, the local
# clone serves as it is and the log says so.
if [ ! -d "\$REPO/.git" ]; then
  git clone "\$REPO_URL" "\$REPO" >> "\$LOG" 2>&1 \
    || fail "Cloning the repository failed. See ~/Library/Logs/verbatim.log"
else
  if git -C "\$REPO" fetch origin main >> "\$LOG" 2>&1; then
    git -C "\$REPO" reset --hard origin/main >> "\$LOG" 2>&1
  else
    echo "offline: serving the clone as it is" >> "\$LOG"
  fi
fi
REV="\$(git -C "\$REPO" rev-parse HEAD 2>/dev/null || echo unknown)"

# The key lives in the environment, never in the instance. A Finder-launched
# app has almost none, so this file stands in for the shell profile.
if [ -f "\$HOME/.config/verbatim/env" ]; then
  set -a; . "\$HOME/.config/verbatim/env"; set +a
fi

# Same revision already serving? Just open the browser.
PID="\$(cat "\$SUPPORT/server.pid" 2>/dev/null || true)"
if [ -n "\$PID" ] && kill -0 "\$PID" 2>/dev/null; then
  if [ "\$(cat "\$SUPPORT/server.rev" 2>/dev/null)" = "\$REV" ]; then
    open "http://127.0.0.1:\$PORT"
    exit 0
  fi
  kill "\$PID" 2>/dev/null
  sleep 1
fi
# Whatever still holds the port is a stale server of ours.
lsof -ti tcp:\$PORT | xargs kill 2>/dev/null
sleep 0.5

( cd "\$REPO" && nohup uv run --project app verbatim "\$INSTANCE" --port "\$PORT" >> "\$LOG" 2>&1 & echo \$! > "\$SUPPORT/server.pid" )
echo "\$REV" > "\$SUPPORT/server.rev"

for _ in {1..120}; do
  curl -s -o /dev/null "http://127.0.0.1:\$PORT" && break
  kill -0 "\$(cat "\$SUPPORT/server.pid")" 2>/dev/null \
    || fail "The server did not start. See ~/Library/Logs/verbatim.log"
  sleep 0.5
done
open "http://127.0.0.1:\$PORT"
LAUNCHER
chmod +x "$APP/Contents/MacOS/verbatim"

echo "built $APP"
echo "  serves   $INSTANCE on http://127.0.0.1:$PORT"
echo "  tracks   $REPO_URL (origin/main, fast-forwarded on every launch)"
echo "  key file ~/.config/verbatim/env (optional, sourced at launch)"
