#!/usr/bin/env bash
# Build Verbatim.app, a native macOS window over this repository.
#
# The executable is a small WKWebView shell (scripts/VerbatimShell.swift),
# compiled here. On launch it runs Resources/start.sh, which keeps a clone
# of the repository under ~/Library/Application Support/Verbatim,
# fast-forwards it to origin/main, and brings the server up on loopback:
# pushing to GitHub is the whole release process for the engine. The shell
# then shows the app in its own window and stops the server on quit. The
# dev checkout you build from is never what the app runs; the clone is.
#
#   scripts/macos-app.sh <instance-dir> [port]
#
# The instance path and port are burned into the app. Rebuild to change
# them, or after editing the shell. Needs macOS with the Xcode command line
# tools (swiftc, sips, iconutil), plus git and uv on the machine running it.
#
# The API key is read from the process environment, never from the instance,
# exactly as everywhere else in this bundle. A launched .app has almost no
# environment, so start.sh sources ~/.config/verbatim/env if it exists; put
# `ANTHROPIC_API_KEY=...` there, chmod 600, and nowhere else.
set -euo pipefail

INSTANCE="${1:?usage: scripts/macos-app.sh <instance-dir> [port]}"
PORT="${2:-8748}"
INSTANCE="$(cd "$INSTANCE" && pwd)"
HERE="$(cd "$(dirname "$0")/.." && pwd)"
REPO_URL="$(git -C "$HERE" remote get-url origin 2>/dev/null \
            || echo "https://github.com/alexis-morain/verbatim-linkedin.git")"

command -v swiftc >/dev/null \
  || { echo "swiftc not found: install the Xcode command line tools" >&2; exit 1; }

APP_HOME="/Applications"
[ -w "$APP_HOME" ] || APP_HOME="$HOME/Applications"
mkdir -p "$APP_HOME"
APP="$APP_HOME/Verbatim.app"

rm -rf "$APP"
mkdir -p "$APP/Contents/MacOS" "$APP/Contents/Resources"

# ---------------------------------------------------------------- the icon
WORK="$(mktemp -d)"
ICONSET="$WORK/verbatim.iconset"
mkdir -p "$ICONSET"
for size in 16 32 128 256 512; do
  sips -z "$size" "$size" "$HERE/assets/icon-1024.png" \
       --out "$ICONSET/icon_${size}x${size}.png" >/dev/null
  double=$((size * 2))
  sips -z "$double" "$double" "$HERE/assets/icon-1024.png" \
       --out "$ICONSET/icon_${size}x${size}@2x.png" >/dev/null
done
iconutil -c icns "$ICONSET" -o "$APP/Contents/Resources/verbatim.icns"

# --------------------------------------------------------------- the shell
cp "$HERE/scripts/VerbatimShell.swift" "$WORK/main.swift"
swiftc -O -o "$APP/Contents/MacOS/Verbatim" "$WORK/main.swift"

# ------------------------------------------------------------- the plist
cat > "$APP/Contents/Info.plist" <<PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"
  "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>CFBundleName</key><string>Verbatim</string>
  <key>CFBundleDisplayName</key><string>Verbatim</string>
  <key>CFBundleIdentifier</key><string>fr.morain.verbatim</string>
  <key>CFBundleVersion</key><string>2.0</string>
  <key>CFBundleExecutable</key><string>Verbatim</string>
  <key>CFBundleIconFile</key><string>verbatim</string>
  <key>CFBundlePackageType</key><string>APPL</string>
  <key>LSMinimumSystemVersion</key><string>12.0</string>
  <key>NSHighResolutionCapable</key><true/>
  <key>VerbatimPort</key><string>$PORT</string>
  <key>NSAppTransportSecurity</key>
  <dict><key>NSAllowsLocalNetworking</key><true/></dict>
</dict>
</plist>
PLIST

# ------------------------------------------------------------- start.sh
# Update the clone, bring the server up, exit 0 only once the port answers.
# The shell shows the window; this script never opens a browser.
cat > "$APP/Contents/Resources/start.sh" <<LAUNCHER
#!/bin/zsh
# Generated by scripts/macos-app.sh. Not hand edited: rebuild instead.
set -u
export PATH="/opt/homebrew/bin:/usr/local/bin:\$HOME/.local/bin:\$PATH"

SUPPORT="\$HOME/Library/Application Support/Verbatim"
REPO="\$SUPPORT/verbatim-linkedin"
LOG="\$HOME/Library/Logs/verbatim.log"
INSTANCE="$INSTANCE"
REPO_URL="$REPO_URL"
PORT=$PORT

fail() {
  /usr/bin/osascript -e "display dialog \\"\$1\\" with title \\"Verbatim\\" buttons {\\"OK\\"} default button 1" >/dev/null 2>&1
  exit 1
}

mkdir -p "\$SUPPORT"
echo "--- launch \$(date '+%Y-%m-%d %H:%M:%S')" >> "\$LOG"

command -v git >/dev/null || fail "git is not installed."
command -v uv  >/dev/null || fail "uv is not installed. See docs.astral.sh/uv"
[ -d "\$INSTANCE" ] || fail "The instance directory is gone: \$INSTANCE. Rebuild the app with scripts/macos-app.sh."

# The update. Every launch tracks origin/main exactly; offline, the local
# clone serves as it is and the log says so.
if [ ! -d "\$REPO/.git" ]; then
  git clone "\$REPO_URL" "\$REPO" >> "\$LOG" 2>&1 \
    || fail "Cloning the repository failed. See ~/Library/Logs/verbatim.log"
else
  if git -C "\$REPO" fetch origin main >> "\$LOG" 2>&1; then
    git -C "\$REPO" reset --hard origin/main >> "\$LOG" 2>&1
  else
    echo "offline: serving the clone as it is" >> "\$LOG"
  fi
fi
REV="\$(git -C "\$REPO" rev-parse HEAD 2>/dev/null || echo unknown)"

# The key lives in the environment, never in the instance. An app launched
# from the Finder has almost none, so this file stands in for the shell
# profile.
if [ -f "\$HOME/.config/verbatim/env" ]; then
  set -a; . "\$HOME/.config/verbatim/env"; set +a
fi

# Same revision already serving? Nothing to do.
PID="\$(cat "\$SUPPORT/server.pid" 2>/dev/null || true)"
if [ -n "\$PID" ] && kill -0 "\$PID" 2>/dev/null; then
  if [ "\$(cat "\$SUPPORT/server.rev" 2>/dev/null)" = "\$REV" ]; then
    exit 0
  fi
  kill "\$PID" 2>/dev/null
  sleep 1
fi
# Whatever still holds the port is a stale server of ours.
STALE="\$(lsof -ti tcp:\$PORT || true)"
[ -n "\$STALE" ] && echo "\$STALE" | xargs kill 2>/dev/null && sleep 0.5

( cd "\$REPO" && nohup uv run --project app verbatim "\$INSTANCE" --port "\$PORT" >> "\$LOG" 2>&1 & echo \$! > "\$SUPPORT/server.pid" )
echo "\$REV" > "\$SUPPORT/server.rev"

for _ in {1..120}; do
  curl -s -o /dev/null "http://127.0.0.1:\$PORT" && exit 0
  kill -0 "\$(cat "\$SUPPORT/server.pid")" 2>/dev/null \
    || fail "The server did not start. See ~/Library/Logs/verbatim.log"
  sleep 0.5
done
fail "The server did not answer within a minute. See ~/Library/Logs/verbatim.log"
LAUNCHER
chmod +x "$APP/Contents/Resources/start.sh"

codesign --force -s - "$APP" >/dev/null 2>&1 || true

echo "built $APP"
echo "  serves   $INSTANCE in its own window, engine on 127.0.0.1:$PORT"
echo "  tracks   $REPO_URL (origin/main, fast-forwarded on every launch)"
echo "  key file ~/.config/verbatim/env (optional, sourced at launch)"
